// SPDX-License-Identifier: MIT
// Offline-only converter. The generated font data remains SIL OFL 1.1.
// clang++ -std=c++17 -O2 scripts/build_stack_digits.cpp -o build/build-stack-digits
// build/build-stack-digits firmware/assets/TouchSansJP.ttf firmware/src/StackDigits.h
#define STB_TRUETYPE_IMPLEMENTATION
#define STBTT_STATIC
#include "../firmware/lib/PaperUI/src/vendor/stb_truetype.h"
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

struct Glyph { int offset, width, height, advance, x, y; };

void generate(std::ostream &out, stbtt_fontinfo &font, const char *name, bool bold) {
  const float scale = stbtt_ScaleForMappingEmToPixels(&font, 48);
  std::vector<unsigned char> packed;
  std::vector<Glyph> glyphs;
  // Only the clock/progress character set is needed; leave other slots empty.
  const std::string supported = " !%-0123456789:";
  for (int c = 32; c <= 58; ++c) {
    Glyph g{};
    g.offset = packed.size();
    int bearing;
    stbtt_GetCodepointHMetrics(&font, c, &g.advance, &bearing);
    g.advance = std::lround(g.advance * scale);
    if (supported.find(char(c)) != std::string::npos && c != ' ') {
      int x1, y1;
      stbtt_GetCodepointBitmapBox(&font, c, scale, scale, &g.x, &g.y, &x1, &y1);
      const int w = x1 - g.x, h = y1 - g.y;
      g.width = w + (bold ? 1 : 0); g.height = h;
      std::vector<unsigned char> raster(w * h);
      stbtt_MakeCodepointBitmap(&font, raster.data(), w, h, w, scale, scale, c);
      const size_t count = size_t(g.width * h);
      packed.resize(packed.size() + (count + 7) / 8, 0);
      for (int y = 0; y < h; ++y) for (int x = 0; x < g.width; ++x) {
        const bool ink = (x < w && raster[y * w + x] >= 128) ||
                        (bold && x > 0 && raster[y * w + x - 1] >= 128);
        const size_t bit = y * g.width + x;
        if (ink) packed[g.offset + bit / 8] |= 0x80 >> (bit % 8);
      }
    }
    glyphs.push_back(g);
  }
  out << "inline const uint8_t " << name << "Bitmap[] = {\n";
  for (size_t i = 0; i < packed.size(); ++i) {
    if (i % 16 == 0) out << "  ";
    out << "0x" << std::hex << std::setw(2) << std::setfill('0') << int(packed[i]) << ",";
    if (i % 16 == 15 || i + 1 == packed.size()) out << '\n';
  }
  out << std::dec << "};\ninline const lgfx::GFXglyph " << name << "Glyphs[] = {\n";
  for (const auto &g : glyphs)
    out << "  {" << g.offset << ',' << g.width << ',' << g.height << ','
        << g.advance << ',' << g.x << ',' << g.y << "},\n";
  out << "};\ninline const lgfx::GFXfont " << name << "{\n"
      << "  const_cast<uint8_t *>(" << name << "Bitmap),\n"
      << "  const_cast<lgfx::GFXglyph *>(" << name << "Glyphs), 32, 58, 56};\n";
}

int main(int argc, char **argv) {
  if (argc != 3) return 2;
  std::ifstream input(argv[1], std::ios::binary);
  std::vector<unsigned char> bytes{std::istreambuf_iterator<char>(input), {}};
  stbtt_fontinfo font{};
  if (bytes.empty() || !stbtt_InitFont(&font, bytes.data(), 0)) return 3;
  std::ofstream out(argv[2], std::ios::binary);
  if (!out) return 4;
  out << "// Generated by scripts/build_stack_digits.cpp; do not edit bitmap data.\n"
      << "// Touch Digits: 48px bitmap subset of TouchSansJP (Noto Sans JP, weight 500).\n"
      << "// Copyright 2014-2021 Adobe. SPDX-License-Identifier: OFL-1.1\n"
      << "// Full copyright, Reserved Font Name and license: ../assets/TouchSansJP-OFL.txt\n"
      << "// Regular and one-pixel horizontal emboldened variants. Not GNU FreeFont.\n"
      << "#pragma once\n#include <M5GFX.h>\nnamespace tc {\n";
  generate(out, font, "stackDigits", false);
  generate(out, font, "stackClockDigits", true);
  out << "} // namespace tc\n";
  return out ? 0 : 5;
}
