[platformio]
default_envs = paper-mono

[env]
platform = espressif32 @ 6.12.0
platform_packages = platformio/framework-arduinoespressif32 @ 3.20017.241212+sha.dcc1105b
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
extra_scripts =
  pre:scripts/public_build_paths.py
  pre:scripts/patch_m5unit_nfc.py
  pre:scripts/embed_default_image.py
board_build.partitions = partitions_16mb_ota_4m_littlefs_7m.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D UART_SCLK_DEFAULT=UART_SCLK_APB
lib_deps =
  bblanchon/ArduinoJson @ 7.4.3
  m5stack/M5Utility @ 0.2.0
  m5stack/M5HAL @ 0.1.2
  m5stack/M5UnitUnified @ 0.5.0
  https://github.com/m5stack/M5Unit-NFC.git#93745b547364f310cd64b5155a870103a7800a5d
  m5stack/M5GFX @ 0.2.27
  m5stack/M5Unified @ 0.2.20
  https://github.com/m5stack/M5PM1.git#be9a5456c007c333e7ac963f33bfde1ffa5d82ee
  https://github.com/m5stack/M5IOE1.git#846eec7d05e25c09013be2acdb8804487f48a62e

[env:paper-mono]
board_build.embed_files = assets/TouchSansJP.ttf
board_build.arduino.memory_type = qio_opi
build_flags = ${env.build_flags} -D TOUCH_CARD_PAPER_MONO=1

[env:stackchan]
board_build.arduino.memory_type = qio_qspi
build_flags = ${env.build_flags} -D TOUCH_CARD_STACKCHAN=1

[env:paper-mono-en]
extends = env:paper-mono
build_flags = ${env:paper-mono.build_flags} -D TOUCH_CARD_DEFAULT_LANGUAGE=1

[env:stackchan-en]
extends = env:stackchan
build_flags = ${env:stackchan.build_flags} -D TOUCH_CARD_DEFAULT_LANGUAGE=1
